### ISSUE TITLE
Runtime errors when trying to run examples

### ISSUE THREAD

**Issue by abetusk** [satyarth/pixelsort#18]
I'm getting `SyntaxError`s when trying to run the examples with the latest build (953a38c894b130932437bd5c0446ad314e2fbc28):

```
$ python3 pixelsort.py examples/image.jpg -i random -c 20
Traceback (most recent call last):
  File "pixelsort.py", line 6, in <module>
    from argparams import parse_args, verify_args
  File "/home/abe/git/github/satyarth/pixelsort/argparams.py", line 88
    logging.info(f"Interval function: {args['interval_function']}")
                                                                 ^
SyntaxError: invalid syntax
```

It looks like spurious `f`s got inserted on various lines from 88 to 100.

Removing those extra characters and I can run the example files.

A pull request will follow unless you get to it before me.

**Comment by satyarth** [comment]
fixed in e43ee84
