### ISSUE TITLE
maximum is completely redundant

### ISSUE THREAD

**Issue by monuszko** [satyarth/pixelsort#7]
While experimenting with pixelsort, I found that some sorting methods (-s) produce very similar results. Intensity is very similar to lightness, but it is actually different' so it's not too bad. `maximum` is much worse.

On all images I've tried, `maximum` produced identical output to `lightness` (default). This is easiest to observe if you run the app with `none` interval method, because it always behaves the same:

python3 pixelsort.py image.jpg -o test.png -i none -s maximum
python3 pixelsort.py image.jpg -o test.png -i none

Digging into it, I read the Wikipedia article on HSV colorspace. "Lightness" sorting method actually returns the "value" of HSV colorspace. "maximum" sorting method of the app takes max(pixel[0], pixel[1], pixel[2]). But how is "lightness" defined in HSV ?

"In the HSV "hexcone" model, value is defined as the largest component of a color, our M above"
https://en.wikipedia.org/wiki/HSL_and_HSV#Lightness

What is "M" ?

M = max(R, G, B)
https://en.wikipedia.org/wiki/HSL_and_HSV#Hue_and_chroma

So, unless I'm missing something, `maximum` and `lightness` look identical to me because they *are* identical, to the point of having the same definition!

**Comment by satyarth** [comment]
Solved with #8
